import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>View Zone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        </h1>

        <p className={styles.description}>
          Тренажер "Поле зрения"
        </p>

        <div className={styles.grid}>
        <span className={styles.card}>
            <h2>Сколько слов за игру</h2>
            <input type="range" />
          </span>

          <span className={styles.card}>
            <h2>Сколько букв в словах</h2>
            <input type="range" />
          </span>

          <span className={styles.card}>
            <h2>Скорость</h2>
            <input type="text" />
            <button>+</button>
            <button>-</button>
          </span>

          <Link href="/game">
            <button>
                Старт
            </button>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
